
import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { useStore, FullClient } from '../../data/store';
import { Plus, Search, MapPin, Phone, Mail, FileText, ToggleLeft, ToggleRight, Building, Printer, ChevronRight, Hash } from 'lucide-react';
import clsx from 'clsx';
import { generateClientPdf } from './utils/generateClientPdf';
import { printPdfBlob } from '../../utils/pdf/printPdf';

export const KlantenPage: React.FC = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const { clients, createClient, toggleClientActive, locations } = useStore();

  const [activeTab, setActiveTab] = useState<'Active' | 'Inactive'>('Active');
  const [searchQuery, setSearchQuery] = useState('');
  const [isModalOpen, setIsModalOpen] = useState(false);

  // Form State
  const [newClient, setNewClient] = useState<Partial<FullClient>>({
    name: '',
    contact: '',
    email: '',
    phone: '',
    address: '',
    vat: '',
    status: 'Active',
    locations: 0
  });

  const filteredClients = clients.filter(c => 
    c.status === activeTab && 
    (c.name.toLowerCase().includes(searchQuery.toLowerCase()) || c.contact.toLowerCase().includes(searchQuery.toLowerCase()))
  );

  const handleCreate = () => {
    if (newClient.name) {
      const client: FullClient = {
        id: `C-${Date.now()}`,
        // clientRef will be auto-generated by store if omitted here
        name: newClient.name,
        contact: newClient.contact || '',
        email: newClient.email || '',
        phone: newClient.phone || '',
        address: newClient.address || '',
        vat: newClient.vat || '',
        status: 'Active',
        locations: 0
      };
      createClient(client);
      setIsModalOpen(false);
      setNewClient({ name: '', contact: '', email: '', phone: '', address: '', vat: '', status: 'Active', locations: 0 });
    }
  };

  const handlePrint = (e: React.MouseEvent, client: FullClient) => {
    e.preventDefault();
    e.stopPropagation();
    const clientLocs = locations.filter(l => l.clientId === client.id);
    const { blob } = generateClientPdf(client, clientLocs);
    printPdfBlob(blob);
  };

  const TabButton = ({ status, label }: { status: 'Active' | 'Inactive'; label: string }) => (
    <button
      onClick={() => setActiveTab(status)}
      className={clsx(
        "pb-3 px-4 text-sm font-bold uppercase tracking-wider border-b-2 transition-all duration-300 flex items-center gap-2",
        activeTab === status 
          ? "border-apex-gold text-white" 
          : "border-transparent text-zinc-500 hover:text-zinc-300 hover:border-zinc-800"
      )}
    >
      {label}
      <span className={clsx(
        "text-[10px] py-0.5 px-2 rounded-full font-mono transition-colors", 
        activeTab === status ? "bg-apex-gold text-black" : "bg-zinc-800 text-zinc-400"
      )}>
        {clients.filter(c => c.status === status).length}
      </span>
    </button>
  );

  return (
    <div className="animate-in fade-in duration-500 pb-20">
      {/* Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-6">
        <div>
          <h2 className="text-3xl font-black text-white uppercase tracking-tight">{t('klanten.title')}</h2>
          <p className="text-zinc-400 mt-1">{t('klanten.subtitle')}</p>
        </div>
        <button 
           onClick={() => setIsModalOpen(true)}
           className="bg-apex-gold text-black px-5 py-2.5 rounded-lg font-bold hover:bg-yellow-500 transition-all shadow-lg shadow-apex-gold/20 flex items-center gap-2 active:scale-95 group"
        >
           <Plus className="w-5 h-5 group-hover:rotate-90 transition-transform" /> 
           <span>{t('klanten.new')}</span>
        </button>
      </div>

      {/* Filters & Search */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-end gap-6 mb-8 border-b border-zinc-800 pb-1">
        <div className="flex space-x-2 w-full sm:w-auto overflow-x-auto no-scrollbar">
          <TabButton status="Active" label={t('klanten.active')} />
          <TabButton status="Inactive" label={t('klanten.inactive')} />
        </div>
        <div className="relative w-full sm:w-72 mb-2 sm:mb-0">
           <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-500" />
           <input 
              type="text" 
              placeholder={t('common.search')}
              value={searchQuery}
              onChange={e => setSearchQuery(e.target.value)}
              className="w-full bg-zinc-900/50 border border-zinc-800 rounded-lg pl-10 pr-4 py-2.5 text-sm text-white focus:border-apex-gold focus:ring-1 focus:ring-apex-gold/50 outline-none transition-all placeholder:text-zinc-600"
           />
        </div>
      </div>

      {/* Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {filteredClients.map(client => {
          // Dynamic location count
          const locCount = locations.filter(l => l.clientId === client.id).length;
          
          return (
            <div 
              key={client.id} 
              onClick={() => navigate(`/klanten/${client.id}`)}
              className="bg-zinc-900/40 backdrop-blur-sm border border-zinc-800/60 rounded-xl p-6 hover:border-apex-gold/30 hover:bg-zinc-900/60 hover:shadow-xl hover:shadow-black/20 transition-all duration-300 group relative overflow-hidden flex flex-col cursor-pointer"
            >
               {/* Glow effect on hover */}
               <div className="absolute inset-0 bg-gradient-to-br from-apex-gold/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500 pointer-events-none" />

               <div className="flex justify-between items-start mb-5 relative z-10">
                  <div className="flex items-center gap-4">
                     <div className="w-12 h-12 bg-zinc-950 rounded-xl flex items-center justify-center text-apex-gold border border-zinc-800 shadow-inner group-hover:scale-105 transition-transform duration-300">
                        <Building className="w-6 h-6" />
                     </div>
                     <div>
                        <h3 className="text-lg font-bold text-white leading-tight group-hover:text-apex-gold transition-colors">{client.name}</h3>
                        <div className="flex flex-col gap-0.5 mt-1">
                            <span className="text-xs text-zinc-500 font-mono tracking-wide">{client.vat || 'Geen BTW nr'}</span>
                            {client.clientRef && (
                                <span className="text-[10px] font-bold text-apex-gold bg-apex-gold/10 px-1.5 rounded w-fit flex items-center gap-1">
                                    <Hash className="w-2.5 h-2.5" /> {client.clientRef}
                                </span>
                            )}
                        </div>
                     </div>
                  </div>
                  
                  <div className="flex gap-1 bg-zinc-950/50 p-1 rounded-lg border border-zinc-800/50 backdrop-blur-md" onClick={e => e.stopPropagation()}>
                      <button 
                         onClick={(e) => handlePrint(e, client)}
                         className="p-1.5 text-zinc-400 hover:text-white hover:bg-zinc-800 rounded-md transition-colors"
                         title={t('klanten.actions.print')}
                      >
                         <Printer className="w-4 h-4" />
                      </button>
                      <button 
                         onClick={() => toggleClientActive(client.id)}
                         className="p-1.5 text-zinc-400 hover:text-white hover:bg-zinc-800 rounded-md transition-colors"
                         title={client.status === 'Active' ? t('klanten.inactive') : t('klanten.active')}
                      >
                         {client.status === 'Active' ? <ToggleRight className="w-4 h-4 text-emerald-500" /> : <ToggleLeft className="w-4 h-4 text-zinc-600" />}
                      </button>
                  </div>
               </div>

               <div className="space-y-3 mb-6 flex-1 relative z-10">
                  <div className="flex items-center gap-3 text-sm text-zinc-400 group-hover:text-zinc-300 transition-colors">
                     <div className="w-6 flex justify-center"><FileText className="w-4 h-4 text-zinc-600 group-hover:text-apex-gold/70 transition-colors" /></div>
                     <span className="truncate">{client.contact || <span className="text-zinc-600 italic">Geen contactpersoon</span>}</span>
                  </div>
                  <div className="flex items-center gap-3 text-sm text-zinc-400 group-hover:text-zinc-300 transition-colors">
                     <div className="w-6 flex justify-center"><Phone className="w-4 h-4 text-zinc-600 group-hover:text-apex-gold/70 transition-colors" /></div>
                     <span className="truncate">{client.phone || <span className="text-zinc-600 italic">Geen telefoon</span>}</span>
                  </div>
                  <div className="flex items-center gap-3 text-sm text-zinc-400 group-hover:text-zinc-300 transition-colors">
                     <div className="w-6 flex justify-center"><Mail className="w-4 h-4 text-zinc-600 group-hover:text-apex-gold/70 transition-colors" /></div>
                     <span className="truncate">{client.email || <span className="text-zinc-600 italic">Geen email</span>}</span>
                  </div>
                  <div className="flex items-center gap-3 text-sm text-zinc-400 group-hover:text-zinc-300 transition-colors">
                     <div className="w-6 flex justify-center"><MapPin className="w-4 h-4 text-zinc-600 group-hover:text-apex-gold/70 transition-colors" /></div>
                     <span className="truncate">{client.address || <span className="text-zinc-600 italic">Geen adres</span>}</span>
                  </div>
               </div>

               <div className="pt-4 border-t border-zinc-800/50 flex items-center justify-between relative z-10" onClick={e => e.stopPropagation()}>
                  <div className="text-xs text-zinc-500 bg-zinc-950/50 px-2 py-1 rounded border border-zinc-800 group-hover:border-zinc-700 transition-colors">
                     <strong className="text-white text-sm mr-1">{locCount}</strong> {t('klanten.locationCount')}
                  </div>
                  <button 
                     onClick={() => navigate(`/klanten/locaties?clientId=${client.id}`)}
                     className="text-xs font-bold text-apex-gold hover:text-white flex items-center gap-1 transition-colors uppercase tracking-wide"
                  >
                     {t('klanten.locatiesBtn')} <ChevronRight className="w-3 h-3" />
                  </button>
               </div>
            </div>
          );
        })}
        {filteredClients.length === 0 && (
           <div className="col-span-full py-16 text-center text-zinc-500 border-2 border-dashed border-zinc-800 rounded-xl bg-zinc-900/20">
              <Building className="w-12 h-12 mx-auto mb-4 opacity-20" />
              <p>{t('klanten.notFound')}</p>
           </div>
        )}
      </div>

      {/* Create Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50 backdrop-blur-md p-4 animate-in fade-in duration-200">
           <div className="bg-zinc-900 border border-zinc-700 p-8 rounded-2xl w-full max-w-lg shadow-2xl relative overflow-hidden">
              {/* Modal Glow */}
              <div className="absolute top-0 right-0 w-32 h-32 bg-apex-gold/10 rounded-full blur-3xl -mr-16 -mt-16 pointer-events-none"></div>

              <h3 className="text-2xl font-black text-white mb-8 flex items-center gap-3">
                 <div className="p-2 bg-apex-gold/10 rounded-lg border border-apex-gold/20">
                    <Plus className="w-6 h-6 text-apex-gold" />
                 </div>
                 {t('klanten.new')}
              </h3>
              
              <div className="space-y-5">
                 <div>
                    <label className="block text-xs font-bold text-zinc-500 uppercase mb-1.5 ml-1">{t('klanten.form.name')} <span className="text-apex-gold">*</span></label>
                    <input 
                       type="text" 
                       value={newClient.name}
                       onChange={e => setNewClient({...newClient, name: e.target.value})}
                       className="w-full bg-zinc-950 border border-zinc-800 rounded-lg p-3 text-white focus:border-apex-gold focus:ring-1 focus:ring-apex-gold/50 outline-none transition-all"
                       placeholder="BVBA Apex..."
                    />
                 </div>
                 <div className="grid grid-cols-2 gap-5">
                    <div>
                       <label className="block text-xs font-bold text-zinc-500 uppercase mb-1.5 ml-1">{t('klanten.form.vat')}</label>
                       <input 
                          type="text" 
                          value={newClient.vat}
                          onChange={e => setNewClient({...newClient, vat: e.target.value})}
                          className="w-full bg-zinc-950 border border-zinc-800 rounded-lg p-3 text-white focus:border-apex-gold focus:ring-1 focus:ring-apex-gold/50 outline-none transition-all font-mono text-sm"
                          placeholder="BE 0..."
                       />
                    </div>
                    <div>
                       <label className="block text-xs font-bold text-zinc-500 uppercase mb-1.5 ml-1">{t('klanten.form.contact')}</label>
                       <input 
                          type="text" 
                          value={newClient.contact}
                          onChange={e => setNewClient({...newClient, contact: e.target.value})}
                          className="w-full bg-zinc-950 border border-zinc-800 rounded-lg p-3 text-white focus:border-apex-gold focus:ring-1 focus:ring-apex-gold/50 outline-none transition-all"
                          placeholder="Naam..."
                       />
                    </div>
                 </div>
                 <div className="grid grid-cols-2 gap-5">
                    <div>
                       <label className="block text-xs font-bold text-zinc-500 uppercase mb-1.5 ml-1">{t('klanten.form.email')}</label>
                       <input 
                          type="email" 
                          value={newClient.email}
                          onChange={e => setNewClient({...newClient, email: e.target.value})}
                          className="w-full bg-zinc-950 border border-zinc-800 rounded-lg p-3 text-white focus:border-apex-gold focus:ring-1 focus:ring-apex-gold/50 outline-none transition-all"
                          placeholder="@bedrijf.be"
                       />
                    </div>
                    <div>
                       <label className="block text-xs font-bold text-zinc-500 uppercase mb-1.5 ml-1">{t('klanten.form.phone')}</label>
                       <input 
                          type="text" 
                          value={newClient.phone}
                          onChange={e => setNewClient({...newClient, phone: e.target.value})}
                          className="w-full bg-zinc-950 border border-zinc-800 rounded-lg p-3 text-white focus:border-apex-gold focus:ring-1 focus:ring-apex-gold/50 outline-none transition-all"
                          placeholder="+32..."
                       />
                    </div>
                 </div>
                 <div>
                    <label className="block text-xs font-bold text-zinc-500 uppercase mb-1.5 ml-1">{t('klanten.form.address')}</label>
                    <input 
                       type="text" 
                       value={newClient.address}
                       onChange={e => setNewClient({...newClient, address: e.target.value})}
                       className="w-full bg-zinc-950 border border-zinc-800 rounded-lg p-3 text-white focus:border-apex-gold focus:ring-1 focus:ring-apex-gold/50 outline-none transition-all"
                       placeholder="Straat, Nr, Postcode Stad"
                    />
                 </div>

                 <div className="flex gap-4 mt-8 pt-4 border-t border-zinc-800">
                    <button 
                       onClick={handleCreate}
                       disabled={!newClient.name}
                       className="flex-1 bg-apex-gold hover:bg-yellow-500 text-black font-bold py-3 px-4 rounded-lg transition-all shadow-lg hover:shadow-apex-gold/20 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                       {t('klanten.form.create')}
                    </button>
                    <button 
                       onClick={() => setIsModalOpen(false)}
                       className="flex-1 bg-zinc-800 hover:bg-zinc-700 text-white font-bold py-3 px-4 rounded-lg transition-colors border border-zinc-700"
                    >
                       {t('klanten.form.cancel')}
                    </button>
                 </div>
              </div>
           </div>
        </div>
      )}
    </div>
  );
};
